### ISSUE TITLE
Export Distribution clarifications

### ISSUE THREAD

**Issue by aigenticus** [edgexfoundry/export-go#11]
Can you please document what works in Export Distribution and what doesn't? Is there an export channel that is functional?
Thanks a lot

**Comment by feclare** [comment]
The only implemented protocols at the moment are http rest and mqtt.

**Comment by aigenticus** [comment]
thanks for your reply @feclare !
which ones are the missing protocols in respect to the Java version? HTTPS and MQTTS?

**Comment by chenchix** [comment]
@rtmaster I have added mqtts, and https was already supported

**Comment by aigenticus** [comment]
Thanks @chenchix you rock!
