### ISSUE TITLE
makefile can't generate the binaries

### ISSUE THREAD

**Issue by feclare** [edgexfoundry/export-go#9]
The binary collides with the client and distro directories. We can fix it like:

1. Renaming again the binaries having the 'export-' prefix
2. Creating the binaries in a 'bin' directory.

what do we prefer?

**Comment by drasko** [comment]
I'd prefer creating binaries in the `build` directory (more precisely putting all build artifacts in `build`)

**Comment by feclare** [comment]
It is fine to me. Will create a PR doing it.

**Comment by feclare** [comment]
Fixed in #12
